export const ADD_ITEM_FAVORITES_START = 'ADD_ITEM_FAVORITES_START';
export const ADD_ITEM_FAVORITES_END = 'ADD_ITEM_FAVORITES_END';
export const REMOVE_ITEM_FAVORITES_END = 'REMOVE_ITEM_FAVORITES_END';
export const GET_CURRENT_ITEM_SUCCESS = 'GET_CURRENT_ITEM_SUCCESS';
export const GET_CURRENT_ITEM_FALSE = 'GET_CURRENT_ITEM_FALSE';
export const ERROR_FAVORITES = 'ERROR_FAVORITES';
