export const SHOW_SIDEBAR_TRUE = 'SHOW_SIDEBAR_TRUE';
export const SHOW_SIDEBAR_FALSE = 'SHOW_SIDEBAR_FALSE';
export const UPDATE_TOKEN_METADATA = 'UPDATE_TOKEN_METADATA';
export const UPDATE_TOKEN_METADATA_ERROR = 'UPDATE_TOKEN_METADATA_ERROR';
