// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.4; 

import "@openzeppelin/contracts/utils/introspection/IERC165.sol";
import "../../access/ITraderControl.sol";

/**
 * Required interface that conforms to the extension contract of ResaleCreater.
 */
interface IRAIR_ResaleCreaterExtension is IERC165, ITraderControl {

    /**
     * @notice set the resaleTokenURI of tokens generated by this extension. Can only be called by traders.
     */
    function setResaleTokenURI(address creator, string calldata uri) external;

    /**
     * @notice set the resaleTokenURI of tokens generated by this extension. Can only be called by traders.
     */
    function setResaleTokenURI(address creator, string calldata uri, bool identical) external;

    /**
     * @notice set the tokenURI of a token generated by this extension. Can only be called by traders.
     */
    function setTokenURI(address creator, uint256 tokenId, string calldata uri) external;

    /**
     * @notice set the tokenURI of multiple tokens generated by this extension. Can only be called by traders.
     */
    function setTokenURI(address creator, uint256[] calldata tokenId, string[] calldata uri) external;

}