import andreMiripolsky from './AndreMiripolsky.webp';
import bruceFenton2 from './BruceFenton2.webp';
import coinAgenda_LOGO from './coinagenda.webp';
import dogTaxSummit from './DogTax_Summit.webp';
import estate_Teammate from './estate_team.webp';
import teammate_2 from './foundation.webp';
import greymanAuthor from './greymanAuthor.webp';
import teammate_6 from './immersiverse_logo.webp';
import markJKohler from './MarkJKohler.webp';
import michaelTerpin from './MichaelTerpin.webp';
import teammate_5 from './movementontheground.webp';
import teammate_1 from './mrlee.webp';
import nFTLA_ICON from './NFTLA_icon.webp';
import nFTNYC_LOGO from './nftnyc_logo.webp';
import nutTeam from './nuts-teammate.webp';
import teammate_4 from './rair-block.webp';
import rairLogoKohler from './RairLogo_Kohler.webp';
import rairLogo_Koholertext from './RairLogo_Koholer-text.webp';
import teammate_8 from './slidelock_team.webp';
import teammate_3 from './south-dig.webp';

export const Teammate_1 = teammate_1;
export const Teammate_2 = teammate_2;
export const Teammate_3 = teammate_3;
export const Teammate_4 = teammate_4;
export const Teammate_5 = teammate_5;
export const Teammate_6 = teammate_6;
export const Teammate_8 = teammate_8;
export const BruceFenton2 = bruceFenton2;
export const NFTLA_ICON = nFTLA_ICON;
export const NFTNYC_LOGO = nFTNYC_LOGO;
export const NutTeam = nutTeam;
export const MichaelTerpin = michaelTerpin;
export const AndreMiripolsky = andreMiripolsky;
export const CoinAgenda_LOGO = coinAgenda_LOGO;
export const Estate_Teammate = estate_Teammate;
export const GreymanAuthor = greymanAuthor;
export const MarkJKohler = markJKohler;
export const DogTax_Summit = dogTaxSummit;
export const RairLogoKohler = rairLogoKohler;
export const RairLogo_Koholertext = rairLogo_Koholertext;
