
export const GET_USER_START = 'GET_USER_START';
export const GET_USER_COMPLETE = 'GET_USER_COMPLETE';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const SET_ADMIN_RIGHTS = 'SET_ADMIN_RIGHTS';