export const SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';
export const SET_CUSTOM_COLORS = 'SET_CUSTOM_COLORS';
export const SET_CUSTOM_LOGOS_DARK = 'SET_CUSTOM_LOGOS_DARK';
export const SET_CUSTOM_LOGOS_LIGHT = 'SET_CUSTOM_LOGOS_LIGHT';
