#!/bin/bash

echo "Starting media-service in prod..."


#!/bin/bash

echo "Starting media servier with PROD boot script"

GCP_PROJECT_ID=$(gcloud config get-value project)

# Manually set this to match the resource names that are generated by Terraform
VAULT_ROLE_ID_RESOURCE_NAME="gke-vault-role-id-media-service"
VAULT_SECRET_ID_RESOURCE_NAME="gke-vault-secret-id-media-service"

SERVICE_ACCOUNT="gke-media-service@rair-market-dev.iam.gserviceaccount.com"

echo "auth list"
gcloud auth list

echo "Getting secret: $VAULT_ROLE_ID_RESOURCE_NAME..."
export VAULT_MEDIA_SERVICE_APP_ROLE_ID=$(gcloud secrets versions access latest --project=$GCP_PROJECT_ID --secret="$VAULT_ROLE_ID_RESOURCE_NAME")

echo "Getting secret: $VAULT_SECRET_ID_RESOURCE_NAME..."
export VAULT_MEDIA_SERVICE_APP_ROLE_SECRET_ID=$(gcloud secrets versions access latest --project=$GCP_PROJECT_ID --secret="$VAULT_SECRET_ID_RESOURCE_NAME")

echo "Getting secret: JWT_SECRET..."
export JWT_SECRET=$(gcloud secrets versions access latest --project=$GCP_PROJECT_ID --secret="$JWT_SECRET_NAME")

# fire the container as normal
echo "Running npm start..."
npm start