import greymanRose from './greyman.webp';
import greyMan from './greyman1.webp';
import greyManNotFun from './not-fun.webp';
import flyinggreyman from './pic1.webp';
import greymanVariants from './pic2.webp';
import greymanMonument from './pic3.webp';
import greymanArmy from './pic5.webp';
import greymanMatrix from './pic6.webp';
import greyManTimes from './pic7.webp';
import PlayImages from './playImg.webp';
import PlayImagesColored from './playImgColored.webp';

export const GreyMan = greyMan;
export const playImages = PlayImages;
export const playImagesColored = PlayImagesColored;
export const GreyManNotFun = greyManNotFun;
export const GreymanRose = greymanRose;
export const Flyinggreyman = flyinggreyman;
export const GreymanVariants = greymanVariants;
export const GreymanMonument = greymanMonument;
export const GreymanArmy = greymanArmy;
export const GreymanMatrix = greymanMatrix;
export const GreyManTimes = greyManTimes;
