#!/bin/bash

CONSOLE_LINE_BREAK="//////////////////////////////////////////////////////////////////////////"

echo ""
echo $CONSOLE_LINE_BREAK
echo "Copying shared backend code folder..."
echo ""

DIR=$(dirname $0)

SHARED_BACKEND_CODE_SOURCE_DIR=$DIR/../shared_backend_code_source/

###############################################################
###############################################################
# Start Rairnode

# Define destination folder
RAIRNODE_DESTINATION_DIR=$DIR/../rairnode/bin/shared_backend_code_generated/

echo "Removing existing generated folder..."
rm -rf $RAIRNODE_DESTINATION_DIR

echo "Copying all files to Rairnode destination..."
# Copy to destination folder
cp -r $SHARED_BACKEND_CODE_SOURCE_DIR $RAIRNODE_DESTINATION_DIR

# Modify each file in destination with warning at the top of the file
find $RAIRNODE_DESTINATION_DIR -type f -exec sh -c '
echo - Adding warning header to $0
cat << EOF > $0
////////////////////////////////////////////////////////////
// WARNING: AUTO GENERATED FILE
//
// DO NOT EDIT THIS FILE DIRECTLY
// 
// Original source file exists in /shared_backend_code_source
// at the root of this repository
// 
// Codegen command: bash commands/generate_shared_code.sh
// 
////////////////////////////////////////////////////////////

$(cat $0)
EOF
' {} \;
# End Rairnode
###############################################################
###############################################################

# Copy this pattern for each shared code destination desitnation

echo ""
echo "Code generation complete!"
echo $CONSOLE_LINE_BREAK
echo ""