#!/bin/bash

DIR=$(dirname "$0")

printf '\n%s\n\n' \
\
"ATTENTION: THE CREDENTIAL FILE GENERATED CONTAINS HIGHLY SENSITIVE DATA!
FOR THIS REASON, IT WILL BE DELETED IMMEDIATELY UPON COMPLETION OF THIS 
SCRIPT AND CANNOT BE VIEWED AGAIN WITHOUT GENERATING NEW CREDENTIALS.
IT IS HIGHLY ADVISED TO STORE THIS INFORMATION IN A SECURE PASSWORD MANAGER.

OUTPUT FILE LOCATED AT:
$OUTPUT_FILE"

read -p "PRESS [ENTER] TO DELETE FILE AND COMPLETE EXECUTION" 

rm $OUTPUT_FILE && exit
