import wallstreetImg from './wallstreet.webp';
import wallstreet1 from './wallstreet1.webp';
import wallstreet2 from './wallstreet2.webp';
import wallstreetA from './wallstreetA.webp';
import wallstreetB from './wallstreetB.webp';
import wallstreetC from './wallstreetC.webp';
import wallstreetCounter from './wallstreetCounter.webp';
import wallstreetD from './wallstreetD.webp';
import wallstreetE from './wallstreetE.webp';
import wallstreetF from './wallstreetF.webp';

export const WallstreetImg = wallstreetImg;
export const WallstreetCounter = wallstreetCounter;
export const WallstreetA = wallstreetA;
export const WallstreetB = wallstreetB;
export const WallstreetC = wallstreetC;
export const WallstreetD = wallstreetD;
export const WallstreetE = wallstreetE;
export const WallstreetF = wallstreetF;
export const Wallstreet1 = wallstreet1;
export const Wallstreet2 = wallstreet2;
