export const GET_DATA_ALL_START = 'GET_DATA_ALL_START';
export const GET_DATA_ALL_COMPLETE = 'GET_DATA_ALL_COMPLETE';
export const GET_DATA_ALL_EMPTY = 'GET_DATA_ALL_EMPTY';
export const GET_DATA_ALL_CLEAR = 'GET_DATA_ALL_CLEAR';
