export const UPLOAD_VIDEO_START = 'UPLOAD_VIDEO_START';
export const UPLOAD_VIDEO_END = 'UPLOAD_VIDEO_END';
export const UPLOAD_VIDEO_ERROR = 'UPLOAD_VIDEO_ERROR';
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';
