export const GET_PROVIDER_START = 'GET_PROVIDER_START';
export const GET_PROVIDER_COMPLETE = 'GET_PROVIDER_COMPLETE';
export const GET_PROVIDER_ERROR = 'GET_PROVIDER_ERROR';

export const GET_TOKEN_START = 'GET_TOKEN_START';
export const GET_TOKEN_COMPLETE = 'GET_TOKEN_COMPLETE';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';

export const GET_PUBLIC_ADDRESS_COMPLETE = 'GET_PUBLIC_ADDRESS_COMPLETE';
