import bandana from './bandana.webp';
import cepk from './cepk.webp';
import digitalMobile from './digital-mobile.webp';
import nft_1 from './exclusive_1.webp';
import nft_2 from './exclusive_2.webp';
import nft_3 from './exclusive_3.webp';
import nft_4 from './image_3.webp';
import nftImage from './main-nft-screen.webp';
import nftMobile_1 from './nft-mobile_1.webp';
import nftMobile_2 from './nft-mobile_2.webp';
import nipseyBg from './nipsey.webp';
import unlockableVideo from './nipsey1.webp';
import pods from './Pods.webp';
import poweredRair from './poweredRair.webp';
import rairTechMobile from './rair_tech_mobile.webp';
import videoPresent from './video-present.webp';

export const NipseyBg = nipseyBg;
export const Nft_1 = nft_1;
export const Nft_2 = nft_2;
export const Nft_3 = nft_3;
export const Nft_4 = nft_4;
export const NftImage = nftImage;
export const UnlockableVideo = unlockableVideo;
export const DigitalMobile = digitalMobile;
export const NftMobile_1 = nftMobile_1;
export const NftMobile_2 = nftMobile_2;
export const VideoPresent = videoPresent;
export const RairTechMobile = rairTechMobile;
export const Bandana = bandana;
export const Pods = pods;
export const Cepk = cepk;
export const PoweredRair = poweredRair;
