//@ts-nocheck
export const GET_CURRENT_PAGE_START = 'GET_CURRENT_PAGE_START';
export const GET_CURRENT_PAGE_COMPLETE = 'GET_CURRENT_PAGE_COMPLETE';
export const GET_CURRENT_PAGE_END = 'GET_CURRENT_PAGE_END';
export const GET_CURRENT_NULL = 'GET_CURRENT_NULL';
