import aboutPagebg1 from './aboutPage_bg-1.webp';
import carstonImage from './carston-hs.webp';
import davidImage from './David.webp';
import edImage from './Ed.webp';
import garrettImage from './GARRETT.webp';
import guntherImage from './Gunther.webp';
import juliaImage from './JULIA.webp';
import martinImage from './Martin.webp';
import matthewImage from './Matthew.webp';
import michaelImage from './MICHAEL.webp';
import rairProd from './rair-prod.webp';
import sethImage from './Seth.webp';

export const aboutPageBackground = aboutPagebg1;
export const David = davidImage;
export const Ed = edImage;
export const Garrett = garrettImage;
export const Martin = martinImage;
export const Julia = juliaImage;
export const Gunther = guntherImage;
export const Matthew = matthewImage;
export const Michael = michaelImage;
export const Seth = sethImage;
export const RairProd = rairProd;
export const Carston = carstonImage;
