# build environment
FROM node:16.13.0 as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . /usr/src/app
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
RUN npm build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]blo   