export const GET_LIST_VIDEOS_START = 'GET_LIST_VIDEOS_START';
export const GET_LIST_VIDEOS_COMPLETE = 'GET_LIST_VIDEOS_COMPLETE';
export const GET_LIST_VIDEOS_TOTAL_CLEAR = 'GET_LIST_VIDEOS_TOTAL_CLEAR';
export const GET_LIST_VIDEOS_TOTAL = 'GET_LIST_VIDEOS_TOTAL';
export const GET_LIST_VIDEOS_ERROR = 'GET_LIST_VIDEOS_ERROR';
export const SET_LOADING = 'SET_LOADING';
