//@ts-nocheck
export const GET_LIST_VIDEOS_START = 'GET_LIST_VIDEOS_START'
export const GET_LIST_VIDEOS_COMPLETE = 'GET_LIST_VIDEOS_COMPLETE'
export const GET_LIST_VIDEOS_ERROR = 'GET_LIST_VIDEOS_ERROR'
export const REFRESH_LIST_VIDEOS = 'REFRESH_LIST_VIDEOS'