export const GET_NFTLIST_START = 'GET_NFTLIST_START';
export const GET_NFTLIST_COMPLETE = 'GET_NFTLIST_COMPLETE';
export const GET_NFT_TOTAL_CLEAR = 'GET_NFT_TOTAL_CLEAR';
export const GET_NFT_LIST_TOTAL = 'GET_NFT_LIST_TOTAL';
export const GET_MEDIA_LIST_START = 'GET_MEDIA_LIST_START';
export const GET_MEDIA_LIST_COMPLETE = 'GET_MEDIA_LIST_COMPLETE';
export const GET_NFT_DATA_ERROR = 'GET_NFT_DATA_ERROR';
export const SET_SELECTED_INDEX = 'SET_SELECTED_INDEX';
