export const SET_CHAIN_ID = 'SET_CHAIN_ID';
export const SET_USER_ADDRESS = 'SET_USER_ADDRESS';
export const SET_PROGRAMMATIC_PROVIDER = 'SET_PROGRAMMATIC_PROVIDER';
export const SET_REAL_CHAIN = 'SET_REAL_CHAIN';