#!/bin/bash

DIR=$(dirname "$0")

OUTPUT_FILE=$DIR/credential_output/rairnode_app_role.credential_output.txt

printf '\n%s\n\n' \
\
"ATTENTION: THE CREDENTIAL FILE GENERATED CONTAINS HIGHLY SENSITIVE DATA!
FOR THIS REASON, IT WILL BE DELETED IMMEDIATELY UPON COMPLETION OF THIS 
SCRIPT AND CANNOT BE VIEWED AGAIN WITHOUT GENERATING NEW CREDENTIALS.
IT IS HIGHLY ADVISED TO STORE THIS INFORMATION IN A SECURE PASSWORD MANAGER." \
\
"PRESS [ANY KEY] TO DELETE FILE AND COMPLETE EXECUTION"

read -s INPUT  
rm $OUTPUT_FILE && exit
