export const GET_RESALES_LIST_START = 'GET_RESALES_LIST_START';
export const GET_RESALES_LIST_COMPLETE = 'GET_RESALES_LIST_COMPLETE';
export const GET_RESALES_LIST_TOTAL_CLEAR = 'GET_RESALES_LIST_TOTAL_CLEAR';
export const GET_RESALES_LIST_TOTAL = 'GET_RESALES_LIST_TOTAL';
export const GET_RESALES_LIST_ERROR = 'GET_RESALES_LIST_ERROR';
export const REFRESH_RESALES_LIST = 'REFRESH_RESALES_LIST';
